services:
  # Aplikasi PHP
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=repo_ebook
      - DB_USER=root
      - DB_PASS=rootpassword
      - BASE_URL=
    depends_on:
      - db

  # Database MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: repo_ebook
    ports:
      - "3307:3306" # Port 3307 di luar agar tidak bentrok dengan MySQL lokal/XAMPP
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # UI untuk manage database (opsional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
